version: '3'
services:
    dev-environment:
        build: .
        volumes:
            - .:/code
        working_dir: /code
        # add ptrace for swift repl
        privileged: true
        cap_add: 
            - SYS_PTRACE